### ISSUE TITLE
sudo docker run --rm --runtime=quark hello-world

### ISSUE THREAD

**Issue by lebron8dong** [QuarkContainer/Quark#1045]
thread 'main' panicked at 'InitUring fail: SysError(22)', src/vmspace/uringMgr.rs:93:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
docker: Error response from daemon: OCI runtime start failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/moby/8a32da8fbf9259f23947f1b72cde646bd663a56e45a132136c9e1c9831d11109/log.json: no such file or directory): /usr/local/bin/quark did not terminate successfully: exit status 255: : unknown.

**Comment by QuarkContainer** [comment]
@lebron8dong could you please let me know the Linux kernel version of the environment? It could be got from command "uname -r"

**Comment by lebron8dong** [comment]
> @lebron8dong could you please let me know the Linux kernel version of the environment? It could be got from command "uname -r"
ubuntu22.04
Linux kernel version：6.5.0-14-generic

**Comment by shrik3** [comment]
I would suggest you check the log first: `/var/log/quark/quark.log`

Also perhaps increase the log level in `config.json`

**Comment by QuarkContainer** [comment]
Looks like there is some different behavior for io_uring in Linux Kernel 6.x than previous versions. Quark is not compaitble with that change so far :-(. Need some debug.

**Comment by shrik3** [comment]
> Looks like there is some different behavior for io_uring in Linux Kernel 6.x than previous versions. Quark is not compaitble with that change so far :-(. Need some debug.

That would explain why quark suddenly stopped working on my machine (perhaps it was a kernel update I don't remember). What's the latest kernel version known to work? 

--- 

If that was indeed breaking changes in the kernel:

["WE DON'T BREAK USERSPACE!"](https://lore.kernel.org/lkml/CA+55aFy98A+LJK4+GWMcbzaa1zsPBRo76q+ioEjbx-uaMKH6Uw@mail.gmail.com/) :(

**Comment by QuarkContainer** [comment]
I don't which exact Linux kernel version leads to such change. My current dev box linux kernel version is 5.15.0-91-generic. It works without any issue.

**Comment by QuarkContainer** [comment]
The Linux 6.5 io_uring doesn't allow mmap a io_uring to fix address. The QKernel IOUring direct sq/cq depeneds on this feature. So it breaks Quark. 

The fix is to disable IOUring direct sq/cq. And it has been checked in.l
