### ISSUE TITLE
is it possible to opt out cuda during compilation?

### ISSUE THREAD

**Issue by shrik3** [QuarkContainer/Quark#1109]
is it possible to opt out cuda dependency? qvisor on the current main branch will not compile where cuda dependency could not be satisfied.

```
  = note: /usr/bin/ld: cannot find -lcuda: No such file or directory
```

**Comment by QuarkContainer** [comment]
@shrik3 So far I didn't find good way to opt out cuda so far. Would you please have a try with following commands to see whether it could workaround the compiler issue?

sudo apt-get install libelf-dev nvidia-driver-535

**Comment by shrik3** [comment]
> @shrik3 So far I didn't find good way to opt out cuda so far. Would you please have a try with following commands to see whether it could workaround the compiler issue?
> 
> sudo apt-get install libelf-dev nvidia-driver-535

thanks for reply.
With cuda dependencies installed, quark builds and runs without issue.  Still, it would be nice if cuda could be optional.

Also it feels like a hassle to install nvidia drivers on a machine that has no nvidia hardware.. :smirk:

**Comment by changhong94** [comment]
Fixed by pr 1164.
