### ISSUE TITLE
armdev: can't emulate mrs

### ISSUE THREAD

**Issue by CharlyYu** [QuarkContainer/Quark#1114]
When I execute `docker run -d --runtime=quark_d ubuntu:latest bash -c "sleep 10000"`, I got this

```
[Print] [1/43c0180000|0] get panic : Some(unhandled sync exception from el0: 0,
can't emulate mrs
 current-context: PtRegs { regs: [0, 1, 47882646708384, 47882646701872, 0, 47882644476288, 140201741123056, 297766311497, 215, 16, 47882645031008, 0, 0, 0, 47882644705280, 47882644652064, 1, 47882645173300, 2, 47882644476288, 47882646695936, 47882646701872, 0, 0, 47882646708384, 0, 0, 0, 0, 140201741122896, 47882645262672], sp: 140201741122896, pc: 47882646260192, pstate: 1610612736, orig_x0: 0, __pad: 0 })
[INFO] [1/850581] hypecall: 8, paras: 43c019f5a8 0 0 0
[Print] [1/43c0180000|0] panic occurred in file 'src/interrupt/aarch64/mod.rs' at line 277

```

**Comment by chl337** [comment]
The log-comment is a bit misleading I'm afraid. It may not be a _mrs_-instruction at all. I will work on that.

**Comment by shrik3** [comment]
> The log-comment is a bit misleading I'm afraid. It may not be a mrs-instruction at all. I will work on that.

This is correct.

currently when a "unknown exception" happens, the exception handler tries to read the user opcode and, if that's a legal MRS instruction, emulate it.

When the handler can't read opcode or when the opcode is not a legal MRS, then that message is printed. Sorry if that is misleading.

**Comment by chl337** [comment]
@shrik3 NP, I'll reform it.

**Comment by chl337** [comment]
@CharlyYu As the title of this issue is a bit misleading, I would suggest that you close this one, apply b3686e921ed19d4f8da57dbc8f5078bda742cb21, and open a new issue with any additional log information that you have.

**Comment by CharlyYu** [comment]
@chl337  The error is now #1113, This error is annoying me a long time.

**Comment by CharlyYu** [comment]
Anyway, I will close this issue.
