### ISSUE TITLE
can't cleanup mounted FS overlays on crashes

### ISSUE THREAD

**Issue by shrik3** [QuarkContainer/Quark#1117]
When testing development builds of quark, the qvisor sometimes can't cleanup the mounted overlays on crashes.

e.g. `lsblk`

```
└─sda3   8:3    0   400G  0 part /var/lib/quark/601e64069e45e23e33e19934f7befa4acc57c1ad3cb62704bb3b2fcb29683045
                                 /var/lib/quark/0e417359e85debb312803533d5418611c1ac00ac2ce2121a6d3ad78321d3afe1
                                 /var/lib/quark/2a51b0f8bd66b20d2ebb9155ee8c4742d83ac1e12293b348a1ded1e0ae870fdb
                                 /var/lib/quark/a49d74a19a735c1f8ca4344544d595d8210835f71d7ca57afdb5604e4c4bcd21
                                 /
```

I know I shouldn't expect quark to do the cleanups when I have to force kill a freezing quark e.g. `sudo kill -9 quark`, but having such residual[1] overlays is annoying. Do you have suggestions @QuarkContainer ?

[1] I can't force `umount` them with `sudo umount -f <mount point>` because "target is busy", also restarting docker and containerd service won't help here. The only thing that works is a lazy `umount -l` but this is still not clean.

**Comment by QuarkContainer** [comment]
Thanks @shrik3 . I have no good way to solve this. What I did is clean the folder after restare the machine :-(

**Comment by shrik3** [comment]
kill -9 the host process (quark or quark_d) seem to clean the mess.
