### ISSUE TITLE
[Clarification] Task clone - CoW

### ISSUE THREAD

**Issue by chl337** [QuarkContainer/Quark#1146]
@QuarkContainer  Does sys_clone use Copy-on-Write, and if it does, does it extend to the page tables, or are the page tables copied? Also, how is the bookkeeping done, and how it is updated if a write event on shared data happens?

**Comment by chl337** [comment]
@QuarkContainer, how are the flags handled if the parent page table is copied?

**Comment by QuarkContainer** [comment]
@chl337 , yes, sys_clone will do the CoW when needs to create new Os Process. The code is at https://github.com/QuarkContainer/Quark/blob/ca73d368684c8f92c68498a5024f8e18725e7cf0/qlib/kernel/memmgr/mm.rs#L1579.

The basic idea is to fork a new pagetable based on the old one. And make both parent/child pagetable point to same memory page and mark all of them as readonly. When parent or child needs to write the page later, it will trigger PF later and then we can do the CoW.

**Comment by chl337** [comment]
@QuarkContainer 

In Unix systems, the task that starts first is the cloned task (optimization, as the child could call exec()). Does Quark also work this way?

**Comment by QuarkContainer** [comment]
@chl337 Yes. Quark has similar behavior. The code is at Task::Clone of task_clone.rs
