### ISSUE TITLE
coding style specs

### ISSUE THREAD

**Issue by shrik3** [QuarkContainer/Quark#1166]
@QuarkContainer  do you have a specification for coding style? If you are already using tools like rustfmt, could you put the config in the repo?

The default config of rustfmt is decent enough, but it may subject to future changes. I suggest we pin it down.

e.g. 

```
rustfmt --print-config current . >  .rustfmt.toml
```

**Comment by QuarkContainer** [comment]
@shrik3, I have no coding style spec. I think it will be good to add that. 

I am new for rustfmt. Would you please let me know how to use it? Actually, I tried to use your command and them runt he rustfmt but it hangs forever :-).

Or would you please create a PR for that and let's check in this?

**Comment by shrik3** [comment]
> I tried to use your command and them runt he rustfmt but it hangs forever :-).

It takes a file name e.g. `rustfmt lib.rs` (you could also apply to the whole codebase but I suggest against this for the moment, because such huge commit would mess with the version control pretty badly)

Normally you would run it automatically via [editor plugins](https://github.com/rust-lang/rustfmt?tab=readme-ov-file#running-rustfmt-from-your-editor).

> Or would you please create a PR for that and let's check in this?

Gladly, I'll open a RFC.

**Comment by QuarkContainer** [comment]
I create a PR https://github.com/QuarkContainer/Quark/pull/1167. Please let me know whether it is ok.

**Comment by shrik3** [comment]
> I create a PR #1167. Please let me know whether it is ok.

haha I was doing the same

**Comment by QuarkContainer** [comment]
@shrik3 Thank you. Let me close mine. :-)
