### ISSUE TITLE
Clarification - User/Kernel Stack per CPU bookkepping

### ISSUE THREAD

**Issue by chl337** [QuarkContainer/Quark#1208]
@QuarkContainer  What is the purpose of storing the User/Kernel stack in per [CPU](https://github.com/QuarkContainer/Quark/blob/4abfe5c89db8c67f821d2673436a9d2d20fba580/qlib/kernel/vcpu.rs#L119). For what I see, it gets stored in various places, e.g. on [clone startup](https://github.com/QuarkContainer/Quark/blob/4abfe5c89db8c67f821d2673436a9d2d20fba580/qkernel/src/kernel_def.rs#L302), but is never queered back. Neither for [user](https://github.com/QuarkContainer/Quark/blob/4abfe5c89db8c67f821d2673436a9d2d20fba580/qlib/kernel/vcpu.rs#L123) or [kernel](https://github.com/QuarkContainer/Quark/blob/4abfe5c89db8c67f821d2673436a9d2d20fba580/qlib/kernel/vcpu.rs#L107).

**Comment by QuarkContainer** [comment]
@chl337  Per CPU User/Kernel stack is for guest user/kernel switch. When a VCpu return from guest user, the VCPU needs to know the current thread's kernel stack to store the user space registers. Please let me know whether it answer your question. :-)

**Comment by chl337** [comment]
Thanks for the response. I will keep the issue open for a bit longer, in case I have a related question.
