### ISSUE TITLE
aarch64: Signals

### ISSUE THREAD

**Issue by chl337** [QuarkContainer/Quark#1211]
~Syscall [_rt_sigreturn_](https://github.com/QuarkContainer/Quark/blob/99b9130d46e616d932705501feba550f628a5e7a/qlib/kernel/threadmgr/task_signals.rs#L1266) not implemented for aarch64.~

EDIT:

- Signals are tested with the tests in [cpython](https://github.com/python/cpython/tree/main/Lib/test).
- Use [Dockerfile](https://git.sr.ht/~ch3lt/QTest) to build test container. (Uncomment or add others)
- Tested on armdev+#1212

EDIT v1:
_test_signal_ seems to be stuck in a repetition of _getitimer()_ calls without making advance.

**Comment by chl337** [comment]
@CharlyYu @QuarkContainer The test '_test_threadsignals_' fails with error:

**thread '1' panicked at 'vcpu run fail: SysError(25)', src/runc/runtime/vm.rs:478:39**

**thread '1' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x400018f234', src/qlib/mem/list_allocator.rs:811:28**

**thread caused non-unwinding panic. aborting.**

**thread '1' panicked at 'qvisor OOM: Heap allocator fails to allocate memory block', src/heap_alloc.rs:127:9**

I think you guys are currently working on a related issue. Please let me know if you have more information.

**Comment by shrik3** [comment]
> Syscall [rt_sigreturn](https://github.com/QuarkContainer/Quark/blob/99b9130d46e616d932705501feba550f628a5e7a/qlib/kernel/threadmgr/task_signals.rs#L1266) not implemented for aarch64.

That function itself is not really different from the existing x86 one and it's trivial add (thanks @QuarkContainer ). However with #1217 , the problem is still that the libc is not smart enough to set up the correct return trampoline in sys_sigaction.

Let's discuss how we can make it work.

**Comment by shrik3** [comment]
> thread '1' panicked at 'qvisor OOM: Heap allocator fails to allocate memory block', src/heap_alloc.rs:127:9

This is interesting. I never see a memory leak before. Do you have a lot of page faults?
