### ISSUE TITLE
rebasing armdev against main

### ISSUE THREAD

**Issue by shrik3** [QuarkContainer/Quark#1224]
> This branch is [116 commits ahead of](https://github.com/QuarkContainer/Quark/compare/main...armdev), [327 commits behind](https://github.com/QuarkContainer/Quark/compare/armdev...main) main. with 72 files changed, 3,705 additions and 1,190 deletions

I think now we have a semi-functional aarch64 port (thanks folks).  Before it's too late, let's set up a plan to merge the armdev into main. Be ready for conflicts. Please see [this](https://github.com/QuarkContainer/Quark/pull/1223/conflicts) to get an idea.

Let's first 

- [x] complete the open PRs on armdev. 
- [x] test and make sure aarch64 is working to some degrees

As for merging, there are maybe 2 or 3 options:
1. directly merge armdev into main, resolve conflicts (yikes) and do testing at the end.
2. rebase armdev first (there are some dirty commits, do you want to redeem yourself?), then do the same.

My head hurts so hard just by looking at the diffs.... ehhhhh . Please help!

@CharlyYu @abel-von @chl337 @QuarkContainer @SchwarzStein  Hark! I beseech thee, summon forth all ye folk of myriad realms! A quest of wisdom doth beckon. Gather 'round, o beings of light and shadow, for the hour is nigh to seek the paths untrodden and the secrets veiled in the mists of time.

**Comment by chl337** [comment]
> 3. rebase `armdev_rebase`  against the diverging point

Noob question: to what do you refer by 'diverging point'?

**Comment by shrik3** [comment]
![image](https://github.com/QuarkContainer/Quark/assets/16338681/23dee54f-b378-4be7-b721-d472fbbd3c8d)

`382472b4` seems to be the diverging point, against which we should rebase our armdev branch first.

**Comment by shrik3** [comment]
checklists tracked in #1231.
