### ISSUE TITLE
busybox container spend more than 140MB memory with runtime of quark

### ISSUE THREAD

**Issue by abel-von** [QuarkContainer/Quark#123]
Hi, I'm trying to reproduce the performance test in the doc, but when I test the memory overhead, I found that the memory cost is too high compared with the doc.

the memory cost is only 11MB for quark, but my result is almost 140MB.

My host kernel  is `Linux localhost.localdomain 5.12.10-1.el8.elrepo.x86_64 #1 SMP Wed Jun 9 16:17:47 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux`

the config of quark is 
```
{
  "DebugLevel"    : "Error",
  "KernelMemSize" : 16,
  "SlowPrint"     : false,
  "LogLevel"      : "Simple",
  "TcpBuffIO"     : true,
  "EnableAIO"     : true,
  "PrintException": false
}
```

**Comment by abel-von** [comment]
```
[root@localhost Quark]# free -m 
              total        used        free      shared  buff/cache   available
Mem:         257541        3426      250493         169        3621      252277
Swap:          4095           0        4095
[root@localhost Quark]# docker run  -d --runtime quark  busybox sh -c "sleep 1000"
acfd3ca353865181c6cc2ed1b798b8c3912563cac7bf649469bea3909c20b363
[root@localhost Quark]# free -m 
              total        used        free      shared  buff/cache   available
Mem:         257541        3554      250353         178        3633      252138
Swap:          4095           0        4095

```

**Comment by QuarkContainer** [comment]
Thank you for question.

I use the "rss" in "ps -aux" out to caculate the memory usage of a container runtime. Please reference https://linuxconfig.org/ps-output-difference-between-vsz-vs-rss-memory-usage.

I use the following command to get the minimal memory usage overhead.

root@brad1:/var/log/quark# docker run -it --runtime=quark --rm busybox
/ # exit

Before type "exit", run following command in another console.
root@brad1:/var/log/quark# ps -aux | grep quark
root       68332  1.1  0.3 1138296 58420 pts/1   Sl+  13:14   0:00 docker run -it --runtime=quark --rm busybox
root       68364  0.1  0.0 107576  4872 ?        Sl   13:14   0:00 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/edc0c14863d474d1fad722c6c036cf6f618c576d48e8c1a7f761bdcf0d4d29ce -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-quark
root       68374 47.6  0.1 4863588 18872 pts/4   SLsl+ 13:14   0:02 /usr/local/bin/quark boot --pipefd 7
root       68451  0.0  0.0  12100   804 pts/2    S+   13:14   0:00 grep --color=auto quark

There will be 2 processes: 
1. containerd-shim: Seems that the memory usage of this process is const.
2.  /usr/local/bin/quark boot --pipefd 7: This is Quark runtime's overhead. Now the "rss" value is 18872 KB. It is a regression. I will file another issue to follow up.

Note: For gvisor, there will be totally 3 processes and kata has 4 processes.

For your command, the output is as below. It takes 20608 KB. Seems that the "sleep" takes extra 1700+ KB. I have no idea why "free -m" takes so much memory. I will dig into it later.

root@brad1:/var/log/quark# docker run  -d --runtime quark  busybox sh -c "sleep 1000"
ec3f3f129b5da5e3cf7b639d8f23dd59454a4d3fbedce5ea51f97685484da1c4
root@brad1:/var/log/quark# ps -aux | grep quark
root       68633  0.0  0.0 107640  4936 ?        Sl   13:14   0:00 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/ec3f3f129b5da5e3cf7b639d8f23dd59454a4d3fbedce5ea51f97685484da1c4 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-quark
root       68643 51.1  0.1 4865636 20608 ?       SLsl 13:14   0:18 /usr/local/bin/quark boot --pipefd 7

**Comment by abel-von** [comment]
On my host, the Quark runtime process has memory overhead up to 106212kB, which is almost 100MB. is there any config that i missed?

**Comment by abel-von** [comment]
```
[root@localhost feng]# docker ps 
CONTAINER ID   IMAGE     COMMAND                CREATED          STATUS          PORTS     NAMES
fa036b9f584f   busybox   "sh -c 'sleep 1000'"   21 seconds ago   Up 21 seconds             infallible_cartwright
[root@localhost feng]# ps aux | grep quark 
root       79741  0.0  0.0 108700  6680 ?        Sl   10:58   0:00 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/fa036b9f584fbf2a94cf9befbda8fd350afdcf493f11e9d52232bfe600e2e0a7 -address /run/containerd/containerd.sock -containerd-binary /usr/local/bin/containerd -runtime-root /var/run/docker/runtime-quark
root       79751  177  0.0 5455660 106212 ?      SLsl 10:58   0:40 /usr/local/bin/quark boot --pipefd 7
```

**Comment by abel-von** [comment]
There are total memory of 251GB on my host, does quark allocate the memory based on the total memory size or not?

**Comment by QuarkContainer** [comment]
That's interesting. My dev box has 16GB memory. 

Quark doesn't allocate memory based on total memory by intention. 

For QKernel, all the memory includes Qkernel heap, memory map are fully managed by Quark. So there should be no any difference for QKernel to allocate memory in different machine.

QVisor's heap memory is not fully managed by Quark. So far, QVisor is using Jemallocator as below. Maybe Jemallocator didn't some optimzation based on system's free memory. 

I am busying on a debug work item. Later, I will dig into this issue later. Would you please have a try if you have time? i.e. comment the 2 lines below to disable the jemalloc.

in qvisor/src/main.rs
fn main() {
    use self::kvmlib::runc::cmd::command::*;

    #[global_allocator]
    static GLOBAL: jemallocator::Jemalloc = jemallocator::Jemalloc;
....

**Comment by abel-von** [comment]
@QuarkContainer  after commenting the jemalloc codes，memory overhead is much smaller，but there are still almost 50MB memory cost on host.
```
[root@localhost feng]# free -m 
              total        used        free      shared  buff/cache   available
Mem:         257541        3648      243716        2313       10176      249875
Swap:          4095           0        4095
[root@localhost feng]# docker run  -d --runtime quark  busybox sh -c "sleep 1000"
2c9edc418b7584ad180d67c43607c9bd50ce2b0c32b144f0c5c14dfaf208febd
[root@localhost feng]# free -m 
              total        used        free      shared  buff/cache   available
Mem:         257541        3691      243662        2323       10188      249820
Swap:          4095           0        4095

```

**Comment by QuarkContainer** [comment]
@abel-von Thank you for the information. After disable the jemalloc, QVisor will use the rust default heap allocator. Based on the test result, very likely the rust default heap allocator will also do the pre-allocation. 

Later, we will try to enable Quark's buddy allocator (used in QKernel now) in QVisor which can fully manage the allocated memory.

**Comment by QuarkContainer** [comment]
@abel-von After enable the Quark's buddy allocator, in my dev boxes with 32GB memory or 16MB, the memory consumption for the busy box is 9.98 MB. 

Now the heap usage is fully controlled by rust runtime. So I believe even in your large memory box, the memory usage will be consistent.

@abel-von Would you please have a try your box?
