### ISSUE TITLE
Quark panic sometimes when start container

### ISSUE THREAD

**Issue by chengchen666** [QuarkContainer/Quark#1282]
Sometimes start quark on my machine, quark will panic, but most of the time works, following is error log:
`[Print] [3/4340360000|0] get panic : Some(hostinodeop has parent)
[Print] [3/4340360000|0] panic occurred in file 'src/qlib/kernel/fs/mount.rs' at line 338`

This is introduced by line: 
`let parent = current.Parent().expect("hostinodeop has parent"); `
in mount.rs file

**Comment by QuarkContainer** [comment]
@chengchen666 could you please let me know the container image information?

**Comment by chengchen666** [comment]
This one: nvcr.io/nvidia/pytorch:24.01-py3. Maybe you can pull directly because this one is open sourced

**Comment by QuarkContainer** [comment]
@chengchen666 I have a commit in the GPUVirtMPI branch. Could you please have a try?
