### ISSUE TITLE
vcpu and /sys/devices/system/cpu design

### ISSUE THREAD

**Issue by QuarkContainer** [QuarkContainer/Quark#1291]
The mpirun might require the /sys/devices/system/cpu implementation to discovere cpus in the system.

reference code /home/brad/project/hwloc/hwloc/topology-linux.c

**Comment by shrik3** [comment]
sys/proc files opened by hwloc example code, in chronical order

```
/sys/devices/system/cpu/online      (e.g. `0-3`)
/proc/cpuinfo
/proc/self/cpuset
/sys/devices/system/cpu/online
/sys/devices/system/cpu
/sys/devices/system/cpu/cpu0/topology/core_cpus
/sys/devices/system/cpu/cpu0/topology/core_id
/sys/devices/system/cpu/cpu0/topology/cluster_cpus
/sys/devices/system/cpu/cpu0/topology/die_cpus
/sys/devices/system/cpu/cpu0/topology/package_cpus
/sys/devices/system/cpu/cpu0/topology/physical_package_id
/sys/devices/system/cpu/cpu0/cache/*        (not necessary?)
```

**Comment by QuarkContainer** [comment]
The issue has been workarounded with https://github.com/QuarkContainer/Quark/pull/1298. 

Change the issue name to vcpu and /sys/devices/system/cpu design.

This issue is related to mpirun. mpirun needs to get the cpu topology from sys/devices/system/cpu. We need a vcpu design for this purpose. There are following challenge

1. IOThread: Quark has a dedicated IO thread which running in host user space to handle host system call. When the container's cpu quota is very small, e.g. 0.1 cpu, the system performance is very low.
2. vCPU affinity: how should we handle the vcpu to host thread to host cpu affinity? And if there is w/o affinity, what's the right information for the /sys/devices/system/cpu design?

**Comment by QuarkContainer** [comment]
Looks like the issue has been fixed. Close this one.
