### ISSUE TITLE
aarch64: vvar or vdso being modified after executing a command.

### ISSUE THREAD

**Issue by CharlyYu** [QuarkContainer/Quark#1305]
I found everytime when I execute bash of ubuntu by `docker exec -ti --runtime=quark_d ubuntu /bin/bash`, The quark will crash because of a pagefault of a same address with a same pc address pointing to the vdso.
so I made this test codes and it also reproduce the issue.

```
#include <stdio.h>
#include <unistd.h>
#include <sys/time.h>
int main()
{
    system("ls -al");
    struct timeval val;
    int ret = gettimeofday(&val, NULL);
    if (ret == -1)
    {
        printf("Error: gettimeofday()\n");
        return ret;
    }

    printf("sec: %ld, usec: %ld\n", val.tv_sec, val.tv_usec);


    return 0;
}
```

I think maybe it is because after we executed a command, the vdso or vvar memories are modified.

**Comment by CharlyYu** [comment]
It turns out that the signal handler set rt_sigreturn address to a wrong address after the vdso being updated.

**Comment by shrik3** [comment]
> It turns out that the signal handler set rt_sigreturn address to a wrong address after the vdso being updated.

sorry for late reply. The vdso sigreturn symbol has a different offset which caused issue. I thought I reported this earlier somewhere (https://github.com/QuarkContainer/Quark/pull/1248 which is replaced by #1292 )  my bad not putting it in an issue.

Because of the offset difference, sigreturn call becomes get time or something.

**Comment by CharlyYu** [comment]
> Because of the offset difference, sigreturn call becomes get time or something.

Yes, I didn't notice that #1292 is working on this, I thought it is just a refactor of codes.

**Comment by chl337** [comment]
@CharlyYu does #1292 works for you?

**Comment by shrik3** [comment]
should have be fixed, please reopen if necessary.
