### ISSUE TITLE
Sys_shmdt does not work correcty in aarch64

### ISSUE THREAD

**Issue by mhomidi** [QuarkContainer/Quark#1332]
Hi,

I was doing some testing with shm syscalls and I figure out. The issue is when we call sys_shmdt, the address of shared memory detached is stored in `arg0`. (Just compare ret value of shmat and `arg0` of shmdt)
```log

[INFO] [1/4540100000|0] (3/3)------get call id sys_shmat arg0:1
[INFO] [1/4540100000|0] (3/3)------Return[0] res is 2b7bf896e000: call id sys_shmat 
[INFO] [1/4540100000|0] (3/3)------get call id sys_shmctl arg0:1
[INFO] [1/4540100000|0] (3/3)------Return[0] res is 0: call id sys_shmctl 
[INFO] [1/4540100000|0] (3/3)------get call id sys_shmdt arg0:2b7bf896e000
[INFO] [1/4540100000|0] (3/3)------Return[0] res is ffffffffffffffea: call id sys_shmdt 
```
but we in the code, we read it from `arg1` which always is 0 in this syscall. 
```rust
// Shmdt implements shmdt(2).
pub fn SysShmdt(task: &mut Task, args: &SyscallArguments) -> Result<i64> {
    let addr = args.arg1 as u64;

    task.mm.DetachShm(task, addr)?;
    return Ok(0);
}

```
So we need to read `addr` from `arg0`:
```rust
let addr = args.arg0 as u64;
```
Then issue will be solved.

**Comment by shrik3** [comment]
On Thu Jul 25, 2024 at 7:35 PM CEST, Hadi Omidi wrote:
> [...]
> but we in the code, we read it from `arg1` which always is 0 in this syscall. 
> ```rust
> // Shmdt implements shmdt(2).
> pub fn SysShmdt(task: &mut Task, args: &SyscallArguments) -> Result<i64> {
>     let addr = args.arg1 as u64;
>
>     task.mm.DetachShm(task, addr)?;
>     return Ok(0);
> }
>
> ```
> So we need to read `addr` from `arg01:
> ```rust
> let addr = args.arg0 as u64;
> ```
> Then issue will be solved. 

Very true. A classic off-by-one; Thanks for the investigation.

https://elixir.bootlin.com/linux/v6.10/source/ipc/shm.c#L1829

-- 
wth
220F 6A50 7BEF 8C33 3B4A 4404 99DE B3B4 1583 4AEF

**Comment by shrik3** [comment]
btw. we have seen similar bugs before. Maybe we should take some effort
to carefully go through each(?) syscall to make sure we don't fat-finger
the APIs

-- 
wth
220F 6A50 7BEF 8C33 3B4A 4404 99DE B3B4 1583 4AEF
