### ISSUE TITLE
Is QKernel POSIX compatible?

### ISSUE THREAD

**Issue by zhuangqh** [QuarkContainer/Quark#14]
QuarkContainer is cool ! There are some well known benchmark tests showing to us, so
I am wondering is it compatible with the full POSIX

**Comment by QuarkContainer** [comment]
The goal of QuarkContainer to be full compatible with Linux and POSIX. So far it supports 200+ System Call. We are working hard to support more system calls.

**Comment by yyb196** [comment]
Will QuarkContainer compatible with linux's /proc and /sys filesystem? @QuarkContainer

**Comment by QuarkContainer** [comment]
Yes. We support part of /proc and /sys, but not all of them now. The support code is at /Quark/qkernel/src/fs/procfs and /Quark/qkernel/src/fs/sys.
