### ISSUE TITLE
CNCF SIG-Runtime Discussion/Presentation?

### ISSUE THREAD

**Issue by raravena80** [QuarkContainer/Quark#15]
Hello Quark team,

I'm one of the co-chairs of the CNCF SIG-Runtime, I'm reaching out and think it would be great for you to present/discuss the project at one of our meetings. An overview of the project would be great.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our agenda or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by QuarkContainer** [comment]
Thank you for reaching out to me. Have contacted with my email address yulin.sun@quarksoft.io.
