### ISSUE TITLE
should we update crate x86_64  to version 1.30+

### ISSUE THREAD

**Issue by Cordius** [QuarkContainer/Quark#21]
Rust 1.52.0-nightly has removed feature `const_in_array_repeat_expressions`.
With latest nightly rust, build Quark will report error:
```rust
error[E0557]: feature has been removed
 --> /home/cordius/.cargo/registry/src/github.com-1ecc6299db9ec823/x86_64-0.12.3/src/lib.rs:9:43
  |
9 | #![cfg_attr(feature = "const_fn", feature(const_in_array_repeat_expressions))]
  |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed due to causing promotable bugs
```
And update crate x86_64 should resolv this problem.

see https://github.com/rust-osdev/x86_64/issues/233

**Comment by QuarkContainer** [comment]
Thank you for the information.

I have upgrade the x86_64 to 0.13.5. The PR is https://github.com/QuarkContainer/Quark/pull/22 and merged to main branch.

I tested it in my current rust nightly version, and it works fine. Sorry that I am sticking in one feature development and can't upgrade my rust nightly version and do the fully test.

Please let me know if there is more issue. And your check-in is also very welcome!

**Comment by QuarkContainer** [comment]
I have upgrade my rust to lastest version rustc 1.53.0-nightly and checked in necessary fixes. Could you please let me know if there are more issues.

**Comment by QuarkContainer** [comment]
Address and workaround the 1.53.0 nightly upgrade crash issue. Fill issue https://github.com/QuarkContainer/Quark/issues/26 to follow up.
