### ISSUE TITLE
Ask for help: Crash with java runtime. 

### ISSUE THREAD

**Issue by QuarkContainer** [QuarkContainer/Quark#49]
Repro steps:

1.  git clone https://github.com/linksgo2011/jmh-reports.git
2.  docker run -it --net=host -v /go/src/github.com/linksgo2011/jmh-reports:/mnt maven:3.8-openjdk-11 /bin/bash
3. In the docker bash terminal: mvn

The issue can be repro when running "javac". The debug steps are as below. The issue is that there are one memory page are marked as PROTO_NONE. But there is an read access later. The code is generated at runtime. 

Need to understand the purpose of the mprotect and when the access will be triggered. So that we know which system call implementation bug leads to this crash.

**Comment by QuarkContainer** [comment]
Debug steps: 
1. Enable error log: in the Quark/config.json, change debug level as "DebugLevel"    : "Debug"
2. Enable interrupt log: In Quark/qkernel/src/interrupt/mod.rs, search PRINT_EXECPTION, and then enable it "pub const PRINT_EXECPTION : bool = true;"
3. Build: make; make install
4. Repro the issue as issue's repro steps
5. check the log in /var/log/quark/quark.log: tail -n 100000 quark.log > quark1.log
6. Open quark1.log and can find following error message consistently.
13:21:19.194 [ERROR] [1/4006620000|28385208] in PageFaultHandler, cr2: e2ff410038, cr3: 40062a3000, isuser = true, error is 100, ss is 1b, cs == 23, eflags = 10246, new ss is 16

here the pagefault with address e2ff410038. The address e2ff410038 is mapped. Need debug.

**Comment by QuarkContainer** [comment]
After fix mprotect bug, there is easy repro as below.

1. git clone https://github.com/linksgo2011/jmh-reports.git
2. docker run -it --net=host -v /go/src/github.com/linksgo2011/jmh-reports:/mnt maven:3.8-openjdk-11 /bin/bash
3. In the docker bash terminal: cd mnt; mvn

the output is the "mvn" application try to read address which is marked as "PROT_NONE" by sys_mprotect

**Comment by QuarkContainer** [comment]
This is bug when running Java runtime. I have repro same issue also for javac when compile a simple helloworld java program. The issue can easily repro but it doesn't repro different log lines. Looks like it is a race condition so that it doesn't triggered in same location. But the failure is same, i.e. try to read a memory which is marked as "PROT_NONE" . The memory is allocated "mmap" and "mprotect" at same code location.

**Comment by QuarkContainer** [comment]
The access to the mprotected page is by design by java runtime. The bug is at signal handling.

**Comment by lubinszARM** [comment]
Hi @QuarkContainer 
Has this issue been fixed?

**Comment by QuarkContainer** [comment]
Yes. This issue is fixed.
