### ISSUE TITLE
EOWNERDEAD during IO_URING_WAKE in Kernel version 5.12

### ISSUE THREAD

**Issue by Akaame** [QuarkContainer/Quark#88]
Per our discussion on Discord and emailing I am creating this issue so it is publicly known. Running docker with quark runtime fails for kernel versions 5.11 and 5.12 (and probably some later patch versions of 5.10) during IO_URING_WAKE returning a SysError(130) which maps to EOWNERDEAD in errno.

I have not tried the latest version of the rust uring library from tokio authors to test if their implementation is working (there have been several commits iouring subsystem in the kernel and to tokio-rs/io-uring/master after you have adapted their code base).

What I have done so far: Tracing the syscalls does not help as this error is thrown from one place anyway.

Possible further actions: Try tokio-rs/io-uring in the latest version of the kernel and look for the discrepancies between their version and "qlib/uring".

**Comment by abel-von** [comment]
I have encountered the same issue with  host kernel version 5.12

**Comment by abel-von** [comment]
I checked linux kernel 5.12 codes, and found that the Wake syscall codes has changed, it will set the variable "summited" to the the input  parameter "to_sumit", and before return it will check the value "summited", if it is not bigger than 0, it will return the error setted before doing wakeup.

```
    if (ctx->flags & IORING_SETUP_SQPOLL) {                                                                                                              
        io_cqring_overflow_flush(ctx, false, NULL, NULL);
                      
        ret = -EOWNERDEAD;
        if (unlikely(ctx->sq_data->thread == NULL)) {
            goto out;
        }             
        if (flags & IORING_ENTER_SQ_WAKEUP)
            wake_up(&ctx->sq_data->wait);
        if (flags & IORING_ENTER_SQ_WAIT) {
            ret = io_sqpoll_wait_sq(ctx);
            if (ret) 
                goto out;
        }             
        submitted = to_submit;
......

    return submitted ? submitted : ret;
```

so after  I changed the input parameter of IOUringEnter, from 0 to 1, it will succeed.

```    pub fn Wake(&self) -> Result<()> {
        let ret = IOUringEnter(self.fd, 1, 0, IORING_ENTER_SQ_WAKEUP);
        if ret < 0 {
            return Err(Error::SysError(-ret as i32))
        }

        return Ok(());
    }
```

**Comment by QuarkContainer** [comment]
@abel-von Thank you. I test your change in my test environment (5.9.0-050900-generic) and didn't find any regression. So I create a PR https://github.com/QuarkContainer/Quark/pull/128 with your change and merge it. 

Please feel free to create PR in future. Thank you!

**Comment by abel-von** [comment]
Well, I just found that in the codes and I am not sure that change of "to_summit" parameter is an approriate way, I am not sure if the change of that parameter will make some  other error. So I just commented here but not summiting the PR.

**Comment by QuarkContainer** [comment]
test in 5.11.0-27-generic and can't repro. Close as fixed.
