### ISSUE TITLE
When calling system call that quark container doesn't support yet

### ISSUE THREAD

**Issue by jokercha** [QuarkContainer/Quark#972]
What happens if I call a system call that is not currently supported by the quark container?

Is the system call of the host kernel bypassed to be called?
Or is it impossible to be called?

**Comment by QuarkContainer** [comment]
If QKernel doesn't the syscall, it will return error. For example, for qkernel doesn't support syscall sys_get_kernel_syms, it will return error code SysErr::ENOSYS. The source doe is as below: https://github.com/QuarkContainer/Quark/blob/c19ea5ec6cc27781ca4ba7f67464dcc6aa7ed2ad/qkernel/src/syscalls/syscalls.rs#L315
