### ISSUE TITLE
How does quarkcontainer intercepts systemcall to make it toward qkernel?

### ISSUE THREAD

**Issue by jokercha** [QuarkContainer/Quark#973]
Hell all,

I just wonder how quark container intercepts systemcall and makes it toward qkernel?

**Comment by QuarkContainer** [comment]
QKernel intercept syscall with exactly same way as Linux kernel, which is through X86-64 syscall. The code is at https://github.com/QuarkContainer/Quark/blob/c19ea5ec6cc27781ca4ba7f67464dcc6aa7ed2ad/qlib/kernel/arch/x86_64/syscall_entry.s#L53C1-L53C15

**Comment by jokercha** [comment]
Thanks for your quick response

This is how i understand it. Is this correct?
- when an aplication in the quack container makes a syscall (e.g., socket open), Qkernel receives system call and then Qkernel invokes the system call implemented in Rust by your team.
- if a system call that is not implemented in Qkernel is invoked, it returns an error.

And, I hava a question.....
i'm curious if it's possible to have only the network-related system calls processed in user space kernel (like Qkernel),
and let all other operations use the host kernel like a normal docker container.
Could you give me any hints related to this?

**Comment by QuarkContainer** [comment]
Yes. You are right for the first system call process. 

For the second part, below is the current design. 

For IO systemm call, QKernel has no block device driver and TCP/IP protocol stack. For the TCP socket operation, it just rely on Host OS TCP socket. For the TCP Socket over RDMA optimization, QKernel could bypass host kernel to gain better performance. For disk file operation, QKernel rely on host OS's file fd.

For the process/thread operation such as clone, thread switch, as Qkernel has "user space thread" (from host OS view), they could full handled in QKernel, i.e. guest OS, without Host OS.

**Comment by QuarkContainer** [comment]
I close the issue. If you have more questions, please reopen it.
