### ISSUE TITLE
Stripped gVisor copyright?

### ISSUE THREAD

**Issue by amscanne** [QuarkContainer/Quark#99]
Neat project!

I work on gVisor. We'd thought about rust in the past and it's pretty amazing that you've got so much plumbing done.

One issue that I would like to raise, however: I noticed that a lot of the code is directly derived from the gVisor code (same comments, same structure, same directory layout) effectively transliterated to rust. There are many examples, but the ELF loader is a good one ([1], [2]). I noticed that you *did* preserve the Copyright only in the VDSO [3] for some reason.

It's awesome and exciting to see the code seeding new things, and I imagine that this is a simple misunderstanding. I'd like to ask that any file that includes content copied or derived from the files of other open source projects should please retain all copyright notices present in the upstream files.

Thanks, and I'm keen to dig in more to what you've made!

[1] https://github.com/QuarkContainer/Quark/blob/main/qkernel/src/loader/elf.rs#L47
[2] https://github.com/google/gvisor/blob/master/pkg/sentry/loader/elf.go#L70
[3] https://github.com/QuarkContainer/Quark/tree/main/vdso

**Comment by QuarkContainer** [comment]
Hi, Adin,

Yes. Those code is directly derived from gVisor code and translate to Rust. We keep the function name, struct name and comments by intention to recognize gVisor's work.

For the code directly copy from gVisor such vdso, we keep the copyright notice. 

I am not sure about the copyright law for the Rust translate part and what's the right way to handle that as it is not common "copy". Can I put in the copyright file in project just like vdso such as "Some code are derived from https://github.com/google/gvisor and translate to rust and  modified to run inside quark."

**Comment by QuarkContainer** [comment]
Close as there is no more response. Please reopen if there is objection.

**Comment by amscanne** [comment]
Thanks for the quick response, and the proposed solution seems good to me (but I'll be careful to note that I'm not a lawyer and this is not legal advice). Re: common "copy" question, copyright continues to apply to all "derived works", not just literal copies and not bound by language.

FWIW, you may want to ensure that "The Quark Authors" and "The gVisor Authors" are defined in the repository. The canonical way to do this is to include an AUTHORS file in the root. E.g. for gVisor, this notes that the authors are Google + all authors listed in the commit history. You may want something similar to ensure that it is defined? (You could also clarify gVisor authors as e.g. the authors up to a specific commit if that is helpful?)
